// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	model "tasktracker/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskStorage is an autogenerated mock type for the TaskStorage type
type MockTaskStorage struct {
	mock.Mock
}

type MockTaskStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskStorage) EXPECT() *MockTaskStorage_Expecter {
	return &MockTaskStorage_Expecter{mock: &_m.Mock}
}

// DeleteTask provides a mock function with given fields: id
func (_m *MockTaskStorage) DeleteTask(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStorage_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskStorage_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - id int
func (_e *MockTaskStorage_Expecter) DeleteTask(id interface{}) *MockTaskStorage_DeleteTask_Call {
	return &MockTaskStorage_DeleteTask_Call{Call: _e.mock.On("DeleteTask", id)}
}

func (_c *MockTaskStorage_DeleteTask_Call) Run(run func(id int)) *MockTaskStorage_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTaskStorage_DeleteTask_Call) Return(_a0 error) *MockTaskStorage_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStorage_DeleteTask_Call) RunAndReturn(run func(int) error) *MockTaskStorage_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTasks provides a mock function with no fields
func (_m *MockTaskStorage) GetAllTasks() ([]model.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStorage_GetAllTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTasks'
type MockTaskStorage_GetAllTasks_Call struct {
	*mock.Call
}

// GetAllTasks is a helper method to define mock.On call
func (_e *MockTaskStorage_Expecter) GetAllTasks() *MockTaskStorage_GetAllTasks_Call {
	return &MockTaskStorage_GetAllTasks_Call{Call: _e.mock.On("GetAllTasks")}
}

func (_c *MockTaskStorage_GetAllTasks_Call) Run(run func()) *MockTaskStorage_GetAllTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskStorage_GetAllTasks_Call) Return(_a0 []model.Task, _a1 error) *MockTaskStorage_GetAllTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStorage_GetAllTasks_Call) RunAndReturn(run func() ([]model.Task, error)) *MockTaskStorage_GetAllTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastTask provides a mock function with no fields
func (_m *MockTaskStorage) GetLastTask() (*model.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStorage_GetLastTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastTask'
type MockTaskStorage_GetLastTask_Call struct {
	*mock.Call
}

// GetLastTask is a helper method to define mock.On call
func (_e *MockTaskStorage_Expecter) GetLastTask() *MockTaskStorage_GetLastTask_Call {
	return &MockTaskStorage_GetLastTask_Call{Call: _e.mock.On("GetLastTask")}
}

func (_c *MockTaskStorage_GetLastTask_Call) Run(run func()) *MockTaskStorage_GetLastTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskStorage_GetLastTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskStorage_GetLastTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStorage_GetLastTask_Call) RunAndReturn(run func() (*model.Task, error)) *MockTaskStorage_GetLastTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function with given fields: id
func (_m *MockTaskStorage) GetTaskByID(id int) (*model.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStorage_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type MockTaskStorage_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - id int
func (_e *MockTaskStorage_Expecter) GetTaskByID(id interface{}) *MockTaskStorage_GetTaskByID_Call {
	return &MockTaskStorage_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", id)}
}

func (_c *MockTaskStorage_GetTaskByID_Call) Run(run func(id int)) *MockTaskStorage_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTaskStorage_GetTaskByID_Call) Return(_a0 *model.Task, _a1 error) *MockTaskStorage_GetTaskByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStorage_GetTaskByID_Call) RunAndReturn(run func(int) (*model.Task, error)) *MockTaskStorage_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTask provides a mock function with given fields: title
func (_m *MockTaskStorage) InsertTask(title string) (int, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for InsertTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStorage_InsertTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTask'
type MockTaskStorage_InsertTask_Call struct {
	*mock.Call
}

// InsertTask is a helper method to define mock.On call
//   - title string
func (_e *MockTaskStorage_Expecter) InsertTask(title interface{}) *MockTaskStorage_InsertTask_Call {
	return &MockTaskStorage_InsertTask_Call{Call: _e.mock.On("InsertTask", title)}
}

func (_c *MockTaskStorage_InsertTask_Call) Run(run func(title string)) *MockTaskStorage_InsertTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskStorage_InsertTask_Call) Return(_a0 int, _a1 error) *MockTaskStorage_InsertTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStorage_InsertTask_Call) RunAndReturn(run func(string) (int, error)) *MockTaskStorage_InsertTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: id, title
func (_m *MockTaskStorage) UpdateTask(id int, title string) error {
	ret := _m.Called(id, title)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(id, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskStorage_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskStorage_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - id int
//   - title string
func (_e *MockTaskStorage_Expecter) UpdateTask(id interface{}, title interface{}) *MockTaskStorage_UpdateTask_Call {
	return &MockTaskStorage_UpdateTask_Call{Call: _e.mock.On("UpdateTask", id, title)}
}

func (_c *MockTaskStorage_UpdateTask_Call) Run(run func(id int, title string)) *MockTaskStorage_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string))
	})
	return _c
}

func (_c *MockTaskStorage_UpdateTask_Call) Return(_a0 error) *MockTaskStorage_UpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskStorage_UpdateTask_Call) RunAndReturn(run func(int, string) error) *MockTaskStorage_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskStorage creates a new instance of MockTaskStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStorage {
	mock := &MockTaskStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
