// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	model "tasktracker/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskStorage is an autogenerated mock type for the TaskStorage type
type MockTaskStorage struct {
	mock.Mock
}

type MockTaskStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskStorage) EXPECT() *MockTaskStorage_Expecter {
	return &MockTaskStorage_Expecter{mock: &_m.Mock}
}

// GetLastTask provides a mock function with no fields
func (_m *MockTaskStorage) GetLastTask() (*model.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStorage_GetLastTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastTask'
type MockTaskStorage_GetLastTask_Call struct {
	*mock.Call
}

// GetLastTask is a helper method to define mock.On call
func (_e *MockTaskStorage_Expecter) GetLastTask() *MockTaskStorage_GetLastTask_Call {
	return &MockTaskStorage_GetLastTask_Call{Call: _e.mock.On("GetLastTask")}
}

func (_c *MockTaskStorage_GetLastTask_Call) Run(run func()) *MockTaskStorage_GetLastTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskStorage_GetLastTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskStorage_GetLastTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStorage_GetLastTask_Call) RunAndReturn(run func() (*model.Task, error)) *MockTaskStorage_GetLastTask_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTask provides a mock function with given fields: title
func (_m *MockTaskStorage) InsertTask(title string) (int, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for InsertTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskStorage_InsertTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTask'
type MockTaskStorage_InsertTask_Call struct {
	*mock.Call
}

// InsertTask is a helper method to define mock.On call
//   - title string
func (_e *MockTaskStorage_Expecter) InsertTask(title interface{}) *MockTaskStorage_InsertTask_Call {
	return &MockTaskStorage_InsertTask_Call{Call: _e.mock.On("InsertTask", title)}
}

func (_c *MockTaskStorage_InsertTask_Call) Run(run func(title string)) *MockTaskStorage_InsertTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskStorage_InsertTask_Call) Return(_a0 int, _a1 error) *MockTaskStorage_InsertTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskStorage_InsertTask_Call) RunAndReturn(run func(string) (int, error)) *MockTaskStorage_InsertTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskStorage creates a new instance of MockTaskStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStorage {
	mock := &MockTaskStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
