// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskHandler is an autogenerated mock type for the TaskHandlerInterface type
type MockTaskHandler struct {
	mock.Mock
}

// GetLastTask provides a mock function with given fields: c
func (_m *MockTaskHandler) GetLastTask(c *gin.Context) {
	_m.Called(c)
}

// PostTask provides a mock function with given fields: c
func (_m *MockTaskHandler) PostTask(c *gin.Context) {
	_m.Called(c)
}

// NewMockTaskHandler creates a new instance of MockTaskHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskHandler {
	mock := &MockTaskHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
