// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	model "tasktracker/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskServiceInterface is an autogenerated mock type for the TaskServiceInterface type
type MockTaskServiceInterface struct {
	mock.Mock
}

type MockTaskServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskServiceInterface) EXPECT() *MockTaskServiceInterface_Expecter {
	return &MockTaskServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: title
func (_m *MockTaskServiceInterface) CreateTask(title string) (*model.Task, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Task, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Task); ok {
		r0 = rf(title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskServiceInterface_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskServiceInterface_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - title string
func (_e *MockTaskServiceInterface_Expecter) CreateTask(title interface{}) *MockTaskServiceInterface_CreateTask_Call {
	return &MockTaskServiceInterface_CreateTask_Call{Call: _e.mock.On("CreateTask", title)}
}

func (_c *MockTaskServiceInterface_CreateTask_Call) Run(run func(title string)) *MockTaskServiceInterface_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskServiceInterface_CreateTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskServiceInterface_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskServiceInterface_CreateTask_Call) RunAndReturn(run func(string) (*model.Task, error)) *MockTaskServiceInterface_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// LastTask provides a mock function with no fields
func (_m *MockTaskServiceInterface) LastTask() (*model.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskServiceInterface_LastTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastTask'
type MockTaskServiceInterface_LastTask_Call struct {
	*mock.Call
}

// LastTask is a helper method to define mock.On call
func (_e *MockTaskServiceInterface_Expecter) LastTask() *MockTaskServiceInterface_LastTask_Call {
	return &MockTaskServiceInterface_LastTask_Call{Call: _e.mock.On("LastTask")}
}

func (_c *MockTaskServiceInterface_LastTask_Call) Run(run func()) *MockTaskServiceInterface_LastTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskServiceInterface_LastTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskServiceInterface_LastTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskServiceInterface_LastTask_Call) RunAndReturn(run func() (*model.Task, error)) *MockTaskServiceInterface_LastTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskServiceInterface creates a new instance of MockTaskServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskServiceInterface {
	mock := &MockTaskServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
