// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "TaskTracker_/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskService is an autogenerated mock type for the TaskServiceInterface type
type MockTaskService struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: title
func (_m *MockTaskService) CreateTask(title string) models.Task {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 models.Task
	if rf, ok := ret.Get(0).(func(string) models.Task); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	return r0
}

// LastTask provides a mock function with no fields
func (_m *MockTaskService) LastTask() (models.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastTask")
	}

	var r0 models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() (models.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() models.Task); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Task)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
