// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "tasktracker/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskStorage is an autogenerated mock type for the TaskStorage type
type MockTaskStorage struct {
	mock.Mock
}

// GetLastTask provides a mock function with no fields
func (_m *MockTaskStorage) GetLastTask() (*models.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastTask")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTask provides a mock function with given fields: title
func (_m *MockTaskStorage) InsertTask(title string) (int, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for InsertTask")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTaskStorage creates a new instance of MockTaskStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStorage {
	mock := &MockTaskStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
